import os
from setuptools import setup, find_packages

setup(
    name="rail-django",
    version="0.1.0",
    description="A Django wrapper framework with pre-configured settings and tools.",
    long_description=open("README.md").read() if os.path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/rail-django",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Django>=4.2.0",
        "graphene>=3.3.0",
        "graphene-django>=3.1.5",
        "django-filter>=24.2",
        "graphene-file-upload>=1.3.0",
        "django-cors-headers>=4.3.0",
        "weasyprint>=60.1",
        "pillow>=10.2.0",
        "PyJWT>=2.8.0",
        "bleach>=6.1.0",
        "psutil>=5.9.0",
        "requests>=2.31.0",
        "pyotp>=2.9.0",
        "qrcode>=7.4.2",
        "openpyxl>=3.1.2",
        "black>=24.1.0",
        "graphql-relay>=3.2.0",
        "pydyf>=0.8.0",
        "packaging>=23.2",
        "PyYAML>=6.0.1",
        "boto3>=1.34.0",
        "twilio>=8.10.0",
        "sentry-sdk>=2.0.0",
        "django-fsm>=2.8.1",
        "django-environ==0.11.2",
    ],
    entry_points={
        "console_scripts": [
            "rail-admin=rail_django.bin.rail_admin:main",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Framework :: Django :: 4.2",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
)
