# Generated by Django 5.x on 2026-02-10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rail_django", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("app_label", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=120)),
                ("template_id", models.CharField(max_length=120)),
                ("template_version", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PARSED", "Parsed"),
                            ("REVIEWING", "Reviewing"),
                            ("VALIDATION_FAILED", "Validation Failed"),
                            ("VALIDATED", "Validated"),
                            ("SIMULATION_FAILED", "Simulation Failed"),
                            ("SIMULATED", "Simulated"),
                            ("COMMITTED", "Committed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="UPLOADED",
                        max_length=32,
                    ),
                ),
                ("uploaded_by_user_id", models.CharField(max_length=128)),
                ("file_name", models.CharField(max_length=255)),
                ("file_format", models.CharField(choices=[("CSV", "CSV"), ("XLSX", "XLSX")], max_length=10)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("create_rows", models.PositiveIntegerField(default=0)),
                ("update_rows", models.PositiveIntegerField(default=0)),
                ("committed_rows", models.PositiveIntegerField(default=0)),
                ("error_report_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "rail_django_import_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row_number", models.PositiveIntegerField()),
                ("source_values", models.JSONField(default=dict)),
                ("edited_values", models.JSONField(default=dict)),
                ("normalized_values", models.JSONField(blank=True, null=True)),
                ("matching_key", models.CharField(blank=True, max_length=255, null=True)),
                ("action", models.CharField(choices=[("CREATE", "Create"), ("UPDATE", "Update")], max_length=10)),
                ("target_record_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("READY", "Ready"),
                            ("LOCKED", "Locked"),
                            ("COMMITTED", "Committed"),
                        ],
                        default="INVALID",
                        max_length=16,
                    ),
                ),
                ("issue_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="rail_django.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "rail_django_import_row",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="ImportSimulationSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("can_commit", models.BooleanField(default=False)),
                ("would_create", models.PositiveIntegerField(default=0)),
                ("would_update", models.PositiveIntegerField(default=0)),
                ("blocking_errors", models.PositiveIntegerField(default=0)),
                ("warnings", models.PositiveIntegerField(default=0)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_snapshots",
                        to="rail_django.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "rail_django_import_simulation_snapshot",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportIssue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                ("field_path", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[("ERROR", "Error"), ("WARNING", "Warning")],
                        default="ERROR",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("suggested_fix", models.TextField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PARSE", "Parse"),
                            ("EDIT", "Edit"),
                            ("VALIDATE", "Validate"),
                            ("SIMULATE", "Simulate"),
                            ("COMMIT", "Commit"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="rail_django.importbatch",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="rail_django.importrow",
                    ),
                ),
            ],
            options={
                "db_table": "rail_django_import_issue",
                "ordering": ["row_number", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"),
                name="rail_django_import_row_unique_batch_row",
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["app_label", "model_name"], name="rail_djang_app_lab_55f7d8_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["status", "created_at"], name="rail_djang_status_747246_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["uploaded_by_user_id", "created_at"], name="rail_djang_uploaded_64dce0_idx"),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["batch", "status"], name="rail_djang_batch_i_de1eaf_idx"),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["batch", "matching_key"], name="rail_djang_batch_i_7cd0a8_idx"),
        ),
        migrations.AddIndex(
            model_name="importissue",
            index=models.Index(fields=["batch", "severity"], name="rail_djang_batch_i_9f40ba_idx"),
        ),
        migrations.AddIndex(
            model_name="importissue",
            index=models.Index(fields=["batch", "stage"], name="rail_djang_batch_i_271462_idx"),
        ),
        migrations.AddIndex(
            model_name="importissue",
            index=models.Index(fields=["batch", "row_number"], name="rail_djang_batch_i_2b3326_idx"),
        ),
        migrations.AddIndex(
            model_name="importsimulationsnapshot",
            index=models.Index(fields=["batch", "executed_at"], name="rail_djang_batch_i_176ccb_idx"),
        ),
    ]

