roles:
  catalog_viewer:
    description: Read-only access to the catalog.
    role_type: functional
    permissions:
      - store.view_product
  catalog_manager:
    description: Manage catalog items.
    role_type: business
    parent_roles:
      - catalog_viewer
    permissions:
      - store.view_product
      - store.add_product
      - store.change_product
      - store.delete_product
  order_viewer:
    description: Read-only access to orders.
    role_type: functional
    permissions:
      - store.view_order
  order_manager:
    description: Create and update orders.
    role_type: business
    parent_roles:
      - order_viewer
    permissions:
      - store.view_order
      - store.add_order
      - store.change_order
  order_admin:
    description: Full control of orders.
    role_type: system
    parent_roles:
      - order_manager
    permissions:
      - store.view_order
      - store.add_order
      - store.change_order
      - store.delete_order
      - store.view_risk_score
      - store.view_customer_pii
    is_system_role: true
    max_users: 5
  finance_analyst:
    description: Access to financial details.
    role_type: business
    permissions:
      - store.view_order
      - store.view_financials
  store_auditor:
    description: Audit and history access for the store domain.
    role_type: functional
    permissions:
      - store.view_order
      - store.view_product
models:
  Customer:
    classifications:
      model:
        - pii
      fields:
        email:
          - pii
        phone_number:
          - pii
        notes:
          - confidential
  Product:
    fields:
      include:
        - id
        - sku
        - name
        - description
        - category
        - tags
        - order_items_count
        - price
        - currency
        - inventory_count
        - weight_grams
        - is_active
        - internal_notes
        - metadata
        - created_at
        - updated_at
      read_only:
        - sku
        - created_at
        - updated_at
      write_only:
        - internal_notes
    filtering:
      quick:
        - name
        - sku
        - category__name
      quick_lookup: icontains
      auto_detect_quick: false
      fields:
        price:
          lookups:
            - gte
            - lte
            - range
          help_text: Filter by list price.
        category__name:
          lookups:
            - icontains
            - exact
          help_text: Filter by category name.
        tags__name:
          lookups:
            - icontains
          help_text: Filter by tag name.
        is_active:
          lookups:
            - exact
          help_text: Filter active products.
    ordering:
      allowed:
        - name
        - price
        - created_at
      default:
        - -created_at
      allow_related: false
    access:
      operations:
        list:
          roles:
            - catalog_viewer
            - catalog_manager
          permissions:
            - store.view_product
          require_authentication: false
          allow_anonymous: true
        retrieve:
          roles:
            - catalog_viewer
            - catalog_manager
          permissions:
            - store.view_product
          require_authentication: false
          allow_anonymous: true
        create:
          roles:
            - catalog_manager
          permissions:
            - store.add_product
          require_authentication: true
        update:
          roles:
            - catalog_manager
          permissions:
            - store.change_product
          require_authentication: true
        delete:
          roles:
            - catalog_manager
          permissions:
            - store.delete_product
          require_authentication: true
        history:
          roles:
            - store_auditor
          permissions:
            - store.view_product
          require_authentication: true
      fields:
        - field: price
          access: read
          visibility: visible
  Order:
    filtering:
      quick:
        - order_number
        - contact_email
        - customer__email
        - shipping_address__city
      quick_lookup: icontains
      auto_detect_quick: false
      fields:
        status:
          lookups:
            - exact
            - in
          choices:
            - - draft
              - Draft
            - - placed
              - Placed
            - - paid
              - Paid
            - - fulfilled
              - Fulfilled
            - - cancelled
              - Cancelled
            - - refunded
              - Refunded
          help_text: Filter by order status.
        total_amount:
          lookups:
            - gte
            - lte
            - range
          help_text: Filter by order totals.
        placed_at:
          lookups:
            - date
            - gte
            - lte
            - range
          help_text: Filter by placement date.
        customer__email:
          lookups:
            - icontains
            - exact
          help_text: Filter by customer email.
        shipping_address__city:
          lookups:
            - icontains
            - exact
          help_text: Filter by shipping city.
      custom:
        overdue: filter_overdue
        high_value: filter_high_value
        has_balance: filter_has_balance
    fields:
      exclude:
        - raw_payload
      read_only:
        - order_number
        - subtotal_amount
        - tax_amount
        - shipping_amount
        - discount_amount
        - total_amount
        - paid_amount
        - placed_at
        - paid_at
        - fulfilled_at
        - created_at
        - updated_at
      write_only:
        - fraud_context
    ordering:
      allowed:
        - placed_at
        - total_amount
        - status
        - customer__last_name
      default:
        - -placed_at
      allow_related: true
    resolvers:
      queries:
        priority_queue: resolve_priority_queue
      mutations:
        mark_paid: resolve_mark_paid
      fields:
        balance_due: resolve_balance_due
    access:
      operations:
        list:
          roles:
            - order_viewer
            - order_manager
            - order_admin
            - finance_analyst
          permissions:
            - store.view_order
          require_authentication: true
          allow_anonymous: false
        retrieve:
          roles:
            - order_viewer
            - order_manager
            - order_admin
            - finance_analyst
          permissions:
            - store.view_order
          condition: can_access_order
          require_authentication: true
          allow_anonymous: false
          deny_message: You do not have access to this order.
        create:
          roles:
            - order_manager
            - order_admin
          permissions:
            - store.add_order
          require_authentication: true
          deny_message: Only order managers can create orders.
        update:
          roles:
            - order_manager
            - order_admin
          permissions:
            - store.change_order
          condition: can_modify_order
          require_authentication: true
          match: all
          deny_message: Only assigned managers can update orders.
        delete:
          roles:
            - order_admin
          permissions:
            - store.delete_order
          require_authentication: true
          deny_message: Only order admins can delete orders.
        history:
          roles:
            - store_auditor
          permissions:
            - store.view_order
          require_authentication: true
      fields:
        - field: payment_token
          access: read
          visibility: visible
          roles:
            - order_admin
        - field: payment_token
          access: read
          visibility: masked
          mask_value: tok_****
        - field: internal_notes
          access: read
          visibility: visible
          roles:
            - order_manager
            - order_admin
        - field: internal_notes
          access: read
          visibility: hidden
        - field: contact_email
          access: read
          visibility: visible
          condition: can_view_contact_email
        - field: contact_email
          access: read
          visibility: redacted
        - field: risk_score
          access: read
          visibility: visible
          permissions:
            - store.view_risk_score
        - field: risk_score
          access: read
          visibility: hidden
    classifications:
      model:
        - transactional
        - financial
      fields:
        contact_email:
          - pii
        payment_token:
          - secret
          - pci
        internal_notes:
          - confidential
        risk_score:
          - risk
        total_amount:
          - financial
