"""Shared constants for import workflow services and schema."""

from __future__ import annotations

from enum import StrEnum

DEFAULT_MAX_ROWS = 10_000
DEFAULT_MAX_FILE_SIZE_BYTES = 25 * 1024 * 1024


class ImportIssueCode(StrEnum):
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    ROW_LIMIT_EXCEEDED = "ROW_LIMIT_EXCEEDED"
    TEMPLATE_VERSION_MISMATCH = "TEMPLATE_VERSION_MISMATCH"
    MISSING_REQUIRED_COLUMN = "MISSING_REQUIRED_COLUMN"
    INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
    DUPLICATE_MATCHING_KEY = "DUPLICATE_MATCHING_KEY"
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


IMPORT_ISSUE_CODES: tuple[str, ...] = tuple(code.value for code in ImportIssueCode)

