# GraphQLMeta configuration for this app.
# Example configuration (copy and edit):
# roles:
#   catalog_viewer:
#     description: Read-only access
#     role_type: functional
#     permissions:
#       - store.view_product
#   catalog_editor:
#     description: Create and update catalog entries
#     role_type: business
#     permissions:
#       - store.add_product
#       - store.change_product
#     parent_roles:
#       - catalog_viewer
# models:
#   store.Product:
#     fields:
#       include:
#         - id
#         - name
#         - sku
#         - price
#         - created_at
#         - updated_at
#       exclude:
#         - internal_notes
#       read_only:
#         - created_at
#         - updated_at
#     filtering:
#       quick:
#         - name
#         - category__name
#       quick_lookup: icontains
#       auto_detect_quick: false
#       fields:
#         status:
#           lookups:
#             - exact
#             - in
#           choices:
#             - draft
#             - active
#         created_at:
#           - gte
#           - lte
#       custom:
#         has_discount: store.graphql_filters.filter_has_discount
#     ordering:
#       allowed:
#         - name
#         - created_at
#         - price
#       default:
#         - -created_at
#       allow_related: true
#     resolvers:
#       queries:
#         featured: store.graphql_resolvers.resolve_featured_products
#       mutations:
#         apply_discount: store.graphql_resolvers.mutate_apply_discount
#       fields:
#         display_name: store.graphql_resolvers.resolve_display_name
#     access:
#       operations:
#         list:
#           roles:
#             - catalog_viewer
#           require_authentication: true
#         retrieve:
#           permissions:
#             - store.view_product
#           condition: store.graphql_guards.can_access_product
#           match: all
#           deny_message: You cannot view this product.
#         create:
#           roles:
#             - catalog_editor
#           permissions:
#             - store.add_product
#           match: all
#       fields:
#         - field: cost_price
#           access: read
#           visibility: masked
#           mask_value: "***"
#           roles:
#             - catalog_editor
#     classifications:
#       model:
#         - inventory
#       fields:
#         cost_price:
#           - financial
roles:
  # Add role definitions here.
models:
  # Add per-model GraphQLMeta config here.
