# Generated by Django 5.2.10 on 2026-02-07 19:38

import rail_django.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("severity", models.CharField(max_length=32)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("request_path", models.TextField(blank=True, null=True)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "additional_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("session_id", models.CharField(blank=True, max_length=128, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MetadataDeployVersionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(default="default", unique=True)),
                ("version", models.CharField(default="init", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rail_django_metadata_deploy_version",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, verbose_name="Code de récupération"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Est utilisé"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Code de récupération",
                "verbose_name_plural": "Codes de récupération",
                "db_table": "rail_django_mfabackupcode",
            },
        ),
        migrations.CreateModel(
            name="MFADevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="Nom de l'appareil"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("totp", "TOTP (Google Authenticator)"),
                            ("sms", "SMS"),
                            ("backup", "Codes de récupération"),
                        ],
                        max_length=20,
                        verbose_name="Type d'appareil",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Clé secrète"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Est actif"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Appareil principal"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil MFA",
                "verbose_name_plural": "Appareils MFA",
                "db_table": "rail_django_mfadevice",
            },
        ),
        migrations.CreateModel(
            name="ReportingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=80, unique=True, verbose_name="Code"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description detaillee"),
                ),
                (
                    "source_app_label",
                    models.CharField(max_length=120, verbose_name="Application source"),
                ),
                (
                    "source_model",
                    models.CharField(max_length=120, verbose_name="Modele source"),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("model", "Modele Django"),
                            ("sql", "SQL"),
                            ("graphql", "GraphQL"),
                            ("python", "Python"),
                        ],
                        default="model",
                        max_length=30,
                        verbose_name="Type de source",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        default=list,
                        help_text="Liste de filtres {field, lookup, value}.",
                        verbose_name="Filtres par defaut",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        default=list,
                        help_text="Colonnes pour regroupements/axes.",
                        verbose_name="Dimensions",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=list,
                        help_text="Agregations (sum, avg, count...).",
                        verbose_name="Mesures",
                    ),
                ),
                (
                    "computed_fields",
                    models.JSONField(
                        default=list,
                        help_text="Formules basees sur dimensions/mesures.",
                        verbose_name="Champs calcules",
                    ),
                ),
                (
                    "ordering",
                    models.JSONField(
                        default=list,
                        help_text="Expressions order_by appliquees lors des executions.",
                        verbose_name="Tri par defaut",
                    ),
                ),
                (
                    "preview_limit",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Limite apercu"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Sections, quick fields, champs favorises.",
                        verbose_name="Metadonnees UI",
                    ),
                ),
                (
                    "last_materialized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Derniere materialisation"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour"),
                ),
            ],
            options={
                "verbose_name": "Jeu de donnees BI",
                "verbose_name_plural": "Jeux de donnees BI",
                "ordering": ["title", "code"],
                "permissions": [
                    ("run_dataset_preview", "Peut executer un apercu de dataset"),
                    ("materialize_dataset", "Peut materialiser un dataset"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportingExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Titre")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("xlsx", "Excel"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Termine"),
                            ("failed", "Echec"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Filtres appliques lors de l export.",
                        verbose_name="Filtres",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot utilise par le frontend (donnees et layout).",
                        verbose_name="Payload",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Erreur")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Debut"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation"),
                ),
            ],
            options={
                "verbose_name": "Export BI",
                "verbose_name_plural": "Exports BI",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=80, unique=True, verbose_name="Code"),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=list,
                        help_text="Disposition des visualisations {visualization_id, position}.",
                        verbose_name="Layout",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=list,
                        help_text="Filtres globaux appliques a toutes les visualisations.",
                        verbose_name="Filtres applicables",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, default="light", max_length=60, verbose_name="Theme"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour"),
                ),
            ],
            options={
                "verbose_name": "Rapport BI",
                "verbose_name_plural": "Rapports BI",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ReportingReportBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=1, verbose_name="Position"),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict,
                        help_text="Coordonnees (x,y,width,height) pour le frontend.",
                        verbose_name="Layout",
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Titre alternatif"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloc de rapport",
                "verbose_name_plural": "Blocs de rapport",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ReportingVisualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, verbose_name="Code")),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("table", "Tableau"),
                            ("bar", "Histogramme"),
                            ("line", "Courbe"),
                            ("pie", "Camembert"),
                            ("kpi", "Indicateur"),
                            ("area", "Aire"),
                            ("pivot", "Pivot"),
                            ("heatmap", "Heatmap"),
                            ("pdf", "Export PDF"),
                        ],
                        default="table",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Axes, colonnes, legende, couleurs.",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        default=list,
                        help_text="Filtres appliques avant l execution.",
                        verbose_name="Filtres par defaut",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=dict,
                        help_text="Preferences de rendu (theme, animations).",
                        verbose_name="Options UI",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Visualisation par defaut"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour"),
                ),
            ],
            options={
                "verbose_name": "Visualisation BI",
                "verbose_name_plural": "Visualisations BI",
                "ordering": ["dataset__title", "title"],
            },
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_name",
                    models.CharField(
                        help_text="The GraphQL type/model name this filter applies to (e.g. 'Order')",
                        max_length=100,
                    ),
                ),
                (
                    "filter_json",
                    models.JSONField(
                        help_text="The JSON representation of the where clause"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="If true, other users can see and use this filter",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SchemaRegistryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("auto_discover", models.BooleanField(default=True)),
                ("apps", models.JSONField(blank=True, default=list)),
                ("models", models.JSONField(blank=True, default=list)),
                ("exclude_models", models.JSONField(blank=True, default=list)),
                (
                    "schema_settings",
                    models.JSONField(
                        default=rail_django.models._default_schema_settings
                    ),
                ),
                (
                    "type_generation_settings",
                    models.JSONField(
                        default=rail_django.models._default_type_generation_settings
                    ),
                ),
                (
                    "query_settings",
                    models.JSONField(
                        default=rail_django.models._default_query_settings
                    ),
                ),
                (
                    "mutation_settings",
                    models.JSONField(
                        default=rail_django.models._default_mutation_settings
                    ),
                ),
                (
                    "subscription_settings",
                    models.JSONField(
                        default=rail_django.models._default_subscription_settings
                    ),
                ),
                (
                    "performance_settings",
                    models.JSONField(
                        default=rail_django.models._default_performance_settings
                    ),
                ),
                (
                    "persisted_query_settings",
                    models.JSONField(
                        default=rail_django.models._default_persisted_query_settings
                    ),
                ),
                (
                    "security_settings",
                    models.JSONField(
                        default=rail_django.models._default_security_settings
                    ),
                ),
                (
                    "plugin_settings",
                    models.JSONField(
                        default=rail_django.models._default_plugin_settings
                    ),
                ),
                (
                    "middleware_settings",
                    models.JSONField(
                        default=rail_django.models._default_middleware_settings
                    ),
                ),
                (
                    "error_handling",
                    models.JSONField(
                        default=rail_django.models._default_error_handling
                    ),
                ),
                (
                    "custom_scalars",
                    models.JSONField(
                        default=rail_django.models._default_custom_scalars
                    ),
                ),
                (
                    "monitoring_settings",
                    models.JSONField(
                        default=rail_django.models._default_monitoring_settings
                    ),
                ),
                (
                    "schema_registry_settings",
                    models.JSONField(
                        default=rail_django.models._default_schema_registry_settings
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rail_django_schema_registry",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchemaSnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_name", models.SlugField()),
                ("version", models.CharField(max_length=50)),
                ("schema_hash", models.CharField(db_index=True, max_length=64)),
                ("schema_sdl", models.TextField(blank=True)),
                ("schema_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rail_django_schema_snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("RETRYING", "Retrying"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "result_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("owner_id", models.CharField(blank=True, max_length=64, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_retries", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Empreinte de l'appareil",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="Nom de l'appareil"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(verbose_name="User agent")),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Est actif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Appareil de confiance",
                "verbose_name_plural": "Appareils de confiance",
                "db_table": "rail_django_trusteddevice",
            },
        ),
    ]
