# Generated by Django 4.2.25 on 2026-01-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rail_django", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("severity", models.CharField(max_length=32)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("request_path", models.TextField(blank=True, null=True)),
                ("request_method", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "additional_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("session_id", models.CharField(blank=True, max_length=128, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
