# Generated by Django 5.2.10 on 2026-02-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rail_django", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mfadevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mfa_devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="mfabackupcode",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_codes",
                to="rail_django.mfadevice",
                verbose_name="Appareil MFA",
            ),
        ),
        migrations.AddField(
            model_name="reportingexportjob",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="export_jobs",
                to="rail_django.reportingdataset",
                verbose_name="Dataset",
            ),
        ),
        migrations.AddField(
            model_name="reportingexportjob",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="export_jobs",
                to="rail_django.reportingreport",
                verbose_name="Rapport",
            ),
        ),
        migrations.AddField(
            model_name="reportingreportblock",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="rail_django.reportingreport",
                verbose_name="Rapport",
            ),
        ),
        migrations.AddField(
            model_name="reportingvisualization",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visualizations",
                to="rail_django.reportingdataset",
                verbose_name="Jeu de donnees",
            ),
        ),
        migrations.AddField(
            model_name="reportingreportblock",
            name="visualization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="rail_django.reportingvisualization",
                verbose_name="Visualisation",
            ),
        ),
        migrations.AddField(
            model_name="reportingreport",
            name="visualizations",
            field=models.ManyToManyField(
                related_name="reports",
                through="rail_django.ReportingReportBlock",
                to="rail_django.reportingvisualization",
                verbose_name="Visualisations",
            ),
        ),
        migrations.AddField(
            model_name="reportingexportjob",
            name="visualization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="export_jobs",
                to="rail_django.reportingvisualization",
                verbose_name="Visualisation",
            ),
        ),
        migrations.AddField(
            model_name="savedfilter",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_filters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schemasnapshotmodel",
            unique_together={("schema_name", "version")},
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trusted_devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportingvisualization",
            unique_together={("dataset", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="reportingreportblock",
            unique_together={("report", "visualization")},
        ),
        migrations.AlterUniqueTogether(
            name="savedfilter",
            unique_together={("name", "created_by", "model_name")},
        ),
    ]
