# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rail_django", "0002_audit_event_model"),
    ]

    operations = []
