# Generated by Django 5.2.10 on 2026-02-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rail_django", "0003_importing_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="importbatch",
            new_name="rail_django_app_lab_f2f1ed_idx",
            old_name="rail_django_imp_app_7de6cc_idx",
        ),
        migrations.RenameIndex(
            model_name="importbatch",
            new_name="rail_django_status_82ed53_idx",
            old_name="rail_django_imp_sta_24bd95_idx",
        ),
        migrations.RenameIndex(
            model_name="importbatch",
            new_name="rail_django_uploade_aa2697_idx",
            old_name="rail_django_imp_upl_9c2f40_idx",
        ),
        migrations.RenameIndex(
            model_name="importissue",
            new_name="rail_django_batch_i_660e5f_idx",
            old_name="rail_django_imp_bat_7aca6c_idx",
        ),
        migrations.RenameIndex(
            model_name="importissue",
            new_name="rail_django_batch_i_ce53b6_idx",
            old_name="rail_django_imp_bat_8d7f12_idx",
        ),
        migrations.RenameIndex(
            model_name="importissue",
            new_name="rail_django_batch_i_33f3d9_idx",
            old_name="rail_django_imp_bat_12de94_idx",
        ),
        migrations.RenameIndex(
            model_name="importrow",
            new_name="rail_django_batch_i_7d0017_idx",
            old_name="rail_django_imp_bat_9dc532_idx",
        ),
        migrations.RenameIndex(
            model_name="importrow",
            new_name="rail_django_batch_i_9881a4_idx",
            old_name="rail_django_imp_bat_58c822_idx",
        ),
        migrations.RenameIndex(
            model_name="importsimulationsnapshot",
            new_name="rail_django_batch_i_6a0c15_idx",
            old_name="rail_django_imp_bat_4d7277_idx",
        ),
    ]
