# Generated by Django 4.2.27 on 2026-01-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rail_django", "0003_schema_versions"),
    ]

    operations = []
