# Generated by Django 4.2.25 on 2026-01-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rail_django", "0003_schema_versions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaRegistryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("auto_discover", models.BooleanField(default=True)),
                ("apps", models.JSONField(blank=True, default=list)),
                ("models", models.JSONField(blank=True, default=list)),
                ("exclude_models", models.JSONField(blank=True, default=list)),
                ("schema_settings", models.JSONField(default=dict)),
                ("type_generation_settings", models.JSONField(default=dict)),
                ("query_settings", models.JSONField(default=dict)),
                ("mutation_settings", models.JSONField(default=dict)),
                ("performance_settings", models.JSONField(default=dict)),
                ("security_settings", models.JSONField(default=dict)),
                ("middleware_settings", models.JSONField(default=dict)),
                ("error_handling", models.JSONField(default=dict)),
                ("custom_scalars", models.JSONField(default=dict)),
                ("monitoring_settings", models.JSONField(default=dict)),
                ("schema_registry_settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rail_django_schema_registry",
                "ordering": ["name"],
            },
        ),
    ]
