# Generated by Django 5.2.13 on 2026-06-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_django", "0005_mediaexportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingVisualizationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=80, unique=True, verbose_name="Code"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="Identifiant du type de visualisation (ex: bar, line, kpi).",
                        max_length=30,
                        verbose_name="Type de visualisation",
                    ),
                ),
                (
                    "config_template",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration avec placeholders {{slot_name}} remplaces lors de l instanciation.",
                        verbose_name="Template de configuration",
                    ),
                ),
                (
                    "dimension_slots",
                    models.JSONField(
                        default=list,
                        help_text="Liste de slots: [{name, role, required, label, help_text}].",
                        verbose_name="Slots dimensions",
                    ),
                ),
                (
                    "metric_slots",
                    models.JSONField(
                        default=list,
                        help_text="Liste de slots: [{name, role, required, label, help_text}].",
                        verbose_name="Slots metriques",
                    ),
                ),
                (
                    "default_options",
                    models.JSONField(
                        default=dict,
                        help_text="Options UI par defaut (theme, animations, couleurs).",
                        verbose_name="Options par defaut",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Tags pour categoriser et rechercher les templates.",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publie"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour"),
                ),
            ],
            options={
                "verbose_name": "Template de visualisation BI",
                "verbose_name_plural": "Templates de visualisation BI",
                "ordering": ["kind", "title"],
            },
        ),
        migrations.AddField(
            model_name="reportingexportjob",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Fichier genere par le renderer (CSV, XLSX, PDF, JSON).",
                null=True,
                upload_to="reporting/exports/%Y/%m/",
                verbose_name="Fichier exporte",
            ),
        ),
        migrations.AddField(
            model_name="reportingexportjob",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Taille du fichier en octets.",
                verbose_name="Taille du fichier",
            ),
        ),
        migrations.AddField(
            model_name="reportingexportjob",
            name="render_options",
            field=models.JSONField(
                default=dict,
                help_text="Options passees au renderer (delimiter, encoding, orientation...).",
                verbose_name="Options de rendu",
            ),
        ),
        migrations.AddField(
            model_name="reportingexportjob",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reporting_export_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Demandeur",
            ),
        ),
        migrations.AlterField(
            model_name="reportingvisualization",
            name="kind",
            field=models.CharField(
                choices=[
                    ("area", "Aire"),
                    ("bar", "Histogramme"),
                    ("donut", "Anneau"),
                    ("funnel", "Entonnoir"),
                    ("heatmap", "Heatmap"),
                    ("line", "Courbe"),
                    ("map", "Carte geographique"),
                    ("pie", "Camembert"),
                    ("radar", "Radar"),
                    ("sankey", "Diagramme de flux"),
                    ("scatter", "Nuage de points"),
                    ("treemap", "Carte proportionnelle"),
                    ("waterfall", "Cascade"),
                    ("pdf", "Export PDF"),
                    ("gauge", "Jauge"),
                    ("kpi", "Indicateur"),
                    ("pivot", "Pivot"),
                    ("table", "Tableau"),
                ],
                default="table",
                max_length=30,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="ReportingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Titre")),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="Expression cron a 5 champs (ex: '0 8 * * *' pour tous les jours a 8h).",
                        max_length=60,
                        verbose_name="Expression cron",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("materialize", "Materialiser"),
                            ("export", "Exporter"),
                            ("alert", "Alerte conditionnelle"),
                        ],
                        default="materialize",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        blank=True,
                        default="csv",
                        help_text="Format de fichier si action=export (csv, json, xlsx, pdf).",
                        max_length=10,
                        verbose_name="Format d export",
                    ),
                ),
                (
                    "alert_condition",
                    models.JSONField(
                        blank=True,
                        help_text='Condition JSON: {metric, op, threshold}. Ex: {"metric": "total", "op": ">", "threshold": 1000}.',
                        null=True,
                        verbose_name="Condition d alerte",
                    ),
                ),
                (
                    "notification_targets",
                    models.JSONField(
                        default=list,
                        help_text="Liste d'emails ou webhooks pour les alertes.",
                        verbose_name="Cibles de notification",
                    ),
                ),
                (
                    "query_spec",
                    models.JSONField(
                        default=dict,
                        help_text="Spec JSON passee a run_query() lors de l execution.",
                        verbose_name="Spec de requete",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Derniere execution"
                    ),
                ),
                (
                    "last_run_status",
                    models.CharField(
                        choices=[
                            ("success", "Succes"),
                            ("failed", "Echec"),
                            ("skipped", "Ignore (condition non remplie)"),
                            ("never", "Jamais execute"),
                        ],
                        default="never",
                        max_length=20,
                        verbose_name="Statut derniere execution",
                    ),
                ),
                (
                    "last_run_message",
                    models.TextField(
                        blank=True, verbose_name="Message derniere execution"
                    ),
                ),
                (
                    "run_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d executions"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise a jour"),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="rail_django.reportingdataset",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planification BI",
                "verbose_name_plural": "Planifications BI",
                "ordering": ["dataset__title", "title"],
            },
        ),
    ]
