# Generated by Django 4.2.27 on 2026-01-11 15:08

from django.db import migrations, models
import rail_django.models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_django", "0005_merge_20260111_1500"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaVersionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("schema_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("migration_files", models.JSONField(default=list)),
                ("rollback_instructions", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "rail_django_schema_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="custom_scalars",
            field=models.JSONField(default=rail_django.models._default_custom_scalars),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="error_handling",
            field=models.JSONField(default=rail_django.models._default_error_handling),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="middleware_settings",
            field=models.JSONField(
                default=rail_django.models._default_middleware_settings
            ),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="monitoring_settings",
            field=models.JSONField(
                default=rail_django.models._default_monitoring_settings
            ),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="mutation_settings",
            field=models.JSONField(
                default=rail_django.models._default_mutation_settings
            ),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="performance_settings",
            field=models.JSONField(
                default=rail_django.models._default_performance_settings
            ),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="query_settings",
            field=models.JSONField(default=rail_django.models._default_query_settings),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="schema_registry_settings",
            field=models.JSONField(
                default=rail_django.models._default_schema_registry_settings
            ),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="schema_settings",
            field=models.JSONField(default=rail_django.models._default_schema_settings),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="security_settings",
            field=models.JSONField(
                default=rail_django.models._default_security_settings
            ),
        ),
        migrations.AlterField(
            model_name="schemaregistrymodel",
            name="type_generation_settings",
            field=models.JSONField(
                default=rail_django.models._default_type_generation_settings
            ),
        ),
    ]
