# Generated by Django 4.2.27 on 2026-01-12 00:00

from django.db import migrations, models
import rail_django.models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_django", "0006_schemaversionmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemaregistrymodel",
            name="persisted_query_settings",
            field=models.JSONField(
                default=rail_django.models._default_persisted_query_settings
            ),
        ),
        migrations.AddField(
            model_name="schemaregistrymodel",
            name="plugin_settings",
            field=models.JSONField(
                default=rail_django.models._default_plugin_settings
            ),
        ),
    ]
