# Generated by Django 4.2.27 on 2026-01-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_django", "0007_schema_registry_persisted_queries"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaSnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_name", models.SlugField(db_index=True, max_length=50)),
                ("version", models.CharField(max_length=50)),
                ("schema_hash", models.CharField(db_index=True, max_length=64)),
                ("schema_sdl", models.TextField(blank=True)),
                ("schema_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rail_django_schema_snapshot",
                "ordering": ["-created_at"],
                "unique_together": {("schema_name", "version")},
            },
        ),
    ]
