# Generated by Django 4.2.27 on 2026-01-13 00:00

from django.db import migrations, models
import rail_django.models


class Migration(migrations.Migration):

    dependencies = [
        ("rail_django", "0008_schema_snapshot_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemaregistrymodel",
            name="subscription_settings",
            field=models.JSONField(
                default=rail_django.models._default_subscription_settings
            ),
        ),
    ]
