# Generated by Django 4.2.27 on 2026-01-23 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rail_django", "0011_saved_filter"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Empreinte de l'appareil",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="Nom de l'appareil"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(verbose_name="User agent")),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Est actif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil de confiance",
                "verbose_name_plural": "Appareils de confiance",
                "db_table": "rail_django_trusteddevice",
            },
        ),
        migrations.CreateModel(
            name="MFADevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=100, verbose_name="Nom de l'appareil"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("totp", "TOTP (Google Authenticator)"),
                            ("sms", "SMS"),
                            ("backup", "Codes de récupération"),
                        ],
                        max_length=20,
                        verbose_name="Type d'appareil",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Clé secrète"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Est actif"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Appareil principal"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil MFA",
                "verbose_name_plural": "Appareils MFA",
                "db_table": "rail_django_mfadevice",
            },
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, verbose_name="Code de récupération"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Est utilisé"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to="rail_django.mfadevice",
                        verbose_name="Appareil MFA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de récupération",
                "verbose_name_plural": "Codes de récupération",
                "db_table": "rail_django_mfabackupcode",
            },
        ),
    ]
